### ISSUE TITLE
Gallery results with massively uneven heights look bad

### ISSUE THREAD

**Issue by cbeer** [projectblacklight/blacklight-gallery#1]
I'm not sure what can be done about this, other than controlling the data displayed in the gallery view a little more closely (e.g. truncating titles). Maybe we should add a gallery-view-specific option for truncation, unless there are other suggestions for making it look reasonable.

**Comment by thatbudakguy** [comment]
it looks like we ended up with a fixed-height strategy and this issue is pretty old, so closing
