### ISSUE TITLE
Improve masonry icon

### ISSUE THREAD

**Issue by jkeck** [projectblacklight/blacklight-gallery#21]
Depends on #20 

The icons below are a bit too large to fit w/ the other glyphicons.  Also, the way to style a .png similarly to a glyphicon in a cross browser compatible way wasn't immediately clear.  In order to not hold-up #20 let's improve this icon as an iterative task.

![icon-masonry](https://cloud.githubusercontent.com/assets/96776/6312276/1353afb8-b928-11e4-8e6c-c78a68f4b255.png)
![icon-masonry 2x](https://cloud.githubusercontent.com/assets/96776/6312277/144fc406-b928-11e4-9e38-fdf3130069a5.png)

**Comment by jkeck** [comment]
cc @jchristo4

**Comment by jchristo4** [comment]
@jkeck  Attached are masonry view icon in slightly smaller sizes (13x13 & 16x16) to match other view glyphicons. Let me know if you need the icon in other sizes. If SVG is a better option to tackle size issue, I can generate a vector version of the icon. 

![icon_masonry_13x13](https://cloud.githubusercontent.com/assets/302258/6325148/7f31408e-baf8-11e4-96df-13b34ce0de95.png)
![icon_masonry_26x26](https://cloud.githubusercontent.com/assets/302258/6325147/7f2d55d2-baf8-11e4-9298-2e857d1e780c.png)
