### ISSUE TITLE
Q: Why openseadragon dependency?

### ISSUE THREAD

**Issue by jrochkind** [projectblacklight/blacklight-gallery#45]
Why is Openseadragon a [dependency of blacklight-gallery](https://github.com/projectblacklight/blacklight-gallery/blob/master/blacklight-gallery.gemspec#L23)?

The README doesn't mention OSD, and the gem doesn't [seem to do too too much](https://github.com/projectblacklight/blacklight-gallery/search?utf8=%E2%9C%93&q=openseadragon&type=) with it, I don't really understand what it's doing or why it's something for blacklight-gallery to do. 

This comes up, because my sufia app ends up with an openseadragon gem dependency. Because the gem is called just `openseadragon`, this prevents me from trying to load the actual openseadragon via bower and rails-assets.  I was going to try it to see if it worked to get the latest version of OSD, which the gem version of openseadragon doesn't have yet. And I don't actually want anything but the OSD js, I don't want the extra helpers in the gem, some of which seem to actually be riiif-specific, but you can use OSD without riiif of course, it's unclear if the gem is really generic openseadragon for any rails app, or something specifically for samvera or riiif using apps.

**Comment by ewlarson** [comment]
Yeah, I'm in total agreement: "Really i'd rather not have blacklight-gallery forcing the openseadragon gem upon me."

**Comment by thatbudakguy** [comment]
i think this was resolved with v3.0.1 making openseadragon optional, so closing.
