### ISSUE TITLE
Styling for slideshow

### ISSUE THREAD

**Issue by jcoyne** [projectblacklight/blacklight-gallery#5]
@cbeer said:

> I have this CSS in spotlight that makes the carousel look a little better (centers the image, adds a dark background..):
> 
> ``` scss
> .item-carousel {
>   .carousel {
>     background-color: #111;
>     text-align: center;
>   }
>   img {
>     margin-left: auto;
>     margin-right: auto;
>   }
> }
> ```
> 
> I think we need to do something like that here, because as-is it doesn't look at great.

**Comment by thatbudakguy** [comment]
this issue is pretty ancient; i think this is more or less the CSS we have now.
