### ISSUE TITLE
Update to work with Blacklight 7 && Bootstrap 4

### ISSUE THREAD

**Issue by jendiamond** [projectblacklight/blacklight-gallery#55]
### We are using Blacklight 7.0.1 && Bootstrap 4 and would like to use the blacklight-gallery
but there are dependency issues

#### Add this line to your Blacklight application's Gemfile:
`gem 'blacklight-gallery'

#### And then execute:
$ `bundle`

```
Resolving dependencies...
Bundler could not find compatible versions for gem "blacklight":
  In snapshot (Gemfile.lock):
    blacklight (= 7.0.1)

  In Gemfile:
    blacklight (~> 7.0.1)

    blacklight-gallery was resolved to 0.0.1, which depends on
      blacklight (>= 5.0.0.pre4, < 6.0)

    blacklight_range_limit (~> 7.0.0) was resolved to 7.0.0, which depends on
      blacklight

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

**Comment by anjackson** [comment]
Using `gem 'blacklight-gallery', github: 'projectblacklight/blacklight-gallery'` works but I assume this is work-in-progress as the alternative view doesn't turn up in the results page.

**Comment by mejackreed** [comment]
This should be resolved and released now. v1.3.0 and v1.4.0
